name:                TEprogramm
version:             0.1.0.0
github:              "GoldenPalladin/TrafExercise"
license:             BSD3
author:              "Yakovlev Pavel"
maintainer:          "p.yakovlev@live.ru"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TEprogramm#readme>

dependencies:
- base >= 4.7 && < 5
- List

library:
  source-dirs: src

executables:
  TEprogramm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TEprogramm

tests:
  TEprogramm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TEprogramm
